x-runnertmpl: &runnertmpl
  build: ./image
  env_file:
    - ./secrets.env
  environment: &runnerenvtmpl
    ORG_NAME: ccl-consulting
    RUNNER_SCOPE: org
    LABELS: linux,x64
    RUNNER_NAME: runnerX
    RUNNER_WORKDIR: /tmp/runner
  security_opt:
    - label:disable
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './tmp/runnerX:/tmp/runner'
  # Expose to runners
  links:
    - earthlybuildkit
  # Grant access to KVM
  devices:
    - /dev/kvm
  cap_add:
    - NET_ADMIN

services:
  earthlybuildkit:
    image: earthly/buildkitd:v0.8.13@sha256:bfe62d2839191629c9ee266233a276f4ea3d8d5b11e2433ff6917e5e310ef7fe
    environment:
      BUILDKIT_TCP_TRANSPORT_ENABLED: 'true'
      BUILDKIT_TLS_ENABLED: 'false'
      EARTHLY_RESET_TMP_DIR: 'true'
    privileged: true
    tty: true
    volumes:
      - '/tmp/github-runners/earthly-buildkit:/tmp/buildkit:rw'

  runner0:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner0:/tmp/runner'
  runner1:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner1:/tmp/runner'
  runner2:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner2
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner2:/tmp/runner'
  runner3:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner3
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner3:/tmp/runner'
  runner4:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner4
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner4:/tmp/runner'
  runner5:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner5:/tmp/runner'
  runner6:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner6
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner6:/tmp/runner'
  runner7:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner7
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner7:/tmp/runner'
  runner8:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner8
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner8:/tmp/runner'
  runner9:
    <<: *runnertmpl
    environment:
      <<: *runnerenvtmpl
      RUNNER_NAME: runner9
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/runner9:/tmp/runner'
